### ISSUE TITLE
Getting error: The MAC signature found in the HTTP request is not the same as any computed signature

### ISSUE THREAD

**Issue by rawbeans** [Rediker-Software/django-azure-storage#1]
When I try to run collectstatic, I get an authentication error: The MAC signature found in the HTTP request is not the same as any computed signature. 

I have outlined the problem [here on stackoverflow](http://stackoverflow.com/questions/30797521/azure-storage-container-api-request-authentication-failing-with-django-app).

Any idea about what is going wrong?

**Comment by kevin-brown** [comment]
I recently ran into this issue when using the `--clear` command alongside `collectstatic`, but I wasn't able to determine why that happened.

This error is common when the system time is off (such that the signature doesn't match) or if the storage keys are incorrect. I would recommend confirming both of those, it's pretty easy to accidentally put an extra character in the storage keys.

**Comment by rawbeans** [comment]
Both of these appear to be ok. As you can see from [this gist of the request/response](https://gist.github.com/anonymous/7f464b355dace9da72ca), the system times are the same.

I have double checked the storage key, and have tried both the primary and secondary keys.

Any ideas of further debugging I can do to look into this? 

Do my request/response headers look normal?

**Comment by rawbeans** [comment]
I was using the setting DEFAULT_FILE_STORAGE instead of STATICFILES_STORAGE. Changing this fixed the issue.
